[Global]
Name = fuzz0.test.server
Info = Fuzzing test server 0
AdminInfo1 = Test Admin
Ports = 6667
Listen = 127.0.0.1

[Limits]
MaxConnectionsIP = 0
PingTimeout = 300
PongTimeout = 300
ConnectRetry = 300

[Options]
DNS = no
Ident = no
PAM = no
